-- ==============================================================================
-- PROMPTFINDER DATABASE SCHEMA REFERENCE
-- ==============================================================================
-- 
-- ⚠️  DIESE DATEI IST NUR ZUR DOKUMENTATION
-- ⚠️  Die Tabellen existieren bereits in Supabase
-- ⚠️  NICHT erneut ausführen!
--
-- Letzte Aktualisierung: Dezember 2024
-- ==============================================================================


-- ==============================================================================
-- 1. SUBSCRIPTIONS (Lemon Squeezy Integration)
-- ==============================================================================

-- Tabelle für Pro-Subscriptions
CREATE TABLE IF NOT EXISTS subscriptions (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Lemon Squeezy IDs
  customer_id TEXT,
  subscription_id TEXT UNIQUE,
  order_id TEXT,
  
  -- Status & Plan
  status TEXT CHECK (status IN ('free', 'active', 'past_due', 'canceled', 'paused')) DEFAULT 'free',
  plan_type TEXT CHECK (plan_type IN ('monthly', 'annual')),
  
  -- Dates
  current_period_start TIMESTAMP WITH TIME ZONE,
  current_period_end TIMESTAMP WITH TIME ZONE,
  canceled_at TIMESTAMP WITH TIME ZONE,
  
  -- Pricing
  amount INTEGER, -- in cents
  currency TEXT DEFAULT 'USD',
  
  -- Customer Portal
  customer_portal_url TEXT,
  
  -- Metadata
  lemon_squeezy_data JSONB,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ==============================================================================
-- 2. CATEGORIES
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  icon TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  workflow_count INTEGER NOT NULL DEFAULT 0
);

-- Seed Data:
-- writing, marketing, business, productivity, career, development


-- ==============================================================================
-- 3. WORKFLOWS (Extended)
-- ==============================================================================

-- Basis-Tabelle (bereits existierend, hier die erweiterten Felder)
-- ALTER TABLE public.workflows ADD COLUMN IF NOT EXISTS:
--   category_id BIGINT REFERENCES public.categories(id)
--   tags TEXT[] DEFAULT '{}'
--   tool TEXT DEFAULT 'any' CHECK (tool IN ('chatgpt', 'claude', 'cursor', 'any'))
--   difficulty TEXT DEFAULT 'beginner' CHECK (difficulty IN ('beginner', 'intermediate', 'advanced'))
--   estimated_minutes INTEGER DEFAULT 5
--   icon TEXT DEFAULT '📝'
--   meta_title TEXT
--   meta_description TEXT
--   featured BOOLEAN DEFAULT FALSE
--   usage_count INTEGER DEFAULT 0
--   status TEXT DEFAULT 'published' CHECK (status IN ('draft', 'published'))
--   sort_order INTEGER DEFAULT 0


-- ==============================================================================
-- 4. USER_STATS (Streak Tracking)
-- ==============================================================================

-- Zusätzliche Spalten in user_stats:
--   current_streak INTEGER DEFAULT 0
--   longest_streak INTEGER DEFAULT 0


-- ==============================================================================
-- 5. WORKFLOW RATINGS
-- ==============================================================================

CREATE TABLE IF NOT EXISTS workflow_ratings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  workflow_id BIGINT NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(workflow_id, user_id)
);


-- ==============================================================================
-- 6. ANONYMOUS USAGE STATS (GDPR-konform)
-- ==============================================================================

-- Tägliche Workflow-Statistiken (keine persönlichen Daten!)
CREATE TABLE IF NOT EXISTS workflow_daily_stats (
  id SERIAL PRIMARY KEY,
  workflow_id TEXT NOT NULL,
  date DATE NOT NULL,
  anonymous_count INTEGER DEFAULT 0,
  logged_in_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(workflow_id, date)
);

-- Globale tägliche Statistiken
CREATE TABLE IF NOT EXISTS global_daily_stats (
  id SERIAL PRIMARY KEY,
  date DATE NOT NULL UNIQUE,
  total_anonymous INTEGER DEFAULT 0,
  total_logged_in INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ==============================================================================
-- HELPER FUNCTIONS
-- ==============================================================================

-- Check if user has active subscription
-- SELECT has_active_subscription(auth.uid());

-- Increment anonymous usage (called via API)
-- SELECT increment_anonymous_usage('workflow-id');


-- ==============================================================================
-- RLS POLICIES SUMMARY
-- ==============================================================================

-- subscriptions: Users can view own, Service role can manage all
-- categories: Public read
-- workflows: Public read (published only)
-- workflow_ratings: Public read, authenticated insert/update/delete own
-- workflow_daily_stats: Service role only
-- global_daily_stats: Service role only

