-- Migration 008: Categories Table and Workflow Extensions
-- Created: 2024-11-30
-- Purpose: Add categories table and extend workflows with SEO, discovery, and organization fields

-- ==============================================================================
-- STEP 1: Create Categories Table
-- ==============================================================================

-- Categories Tabelle
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  icon TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  workflow_count INTEGER NOT NULL DEFAULT 0
);

-- RLS aktivieren
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Public Read Policy (jeder kann Kategorien lesen)
CREATE POLICY "Categories are viewable by everyone" 
ON public.categories FOR SELECT 
USING (true);

-- Index für Performance
CREATE INDEX IF NOT EXISTS idx_categories_slug ON public.categories(slug);
CREATE INDEX IF NOT EXISTS idx_categories_sort_order ON public.categories(sort_order);

-- ==============================================================================
-- STEP 2: Extend Workflows Table
-- ==============================================================================

-- Neue Spalten hinzufügen
ALTER TABLE public.workflows
ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES public.categories(id),
ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS tool TEXT DEFAULT 'any',
ADD COLUMN IF NOT EXISTS difficulty TEXT DEFAULT 'beginner',
ADD COLUMN IF NOT EXISTS estimated_minutes INTEGER DEFAULT 5,
ADD COLUMN IF NOT EXISTS icon TEXT DEFAULT '📝',
ADD COLUMN IF NOT EXISTS meta_title TEXT,
ADD COLUMN IF NOT EXISTS meta_description TEXT,
ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS usage_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'draft',
ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;

-- Constraints für gültige Werte
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'valid_tool'
  ) THEN
    ALTER TABLE public.workflows
    ADD CONSTRAINT valid_tool CHECK (tool IN ('chatgpt', 'claude', 'cursor', 'any'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'valid_difficulty'
  ) THEN
    ALTER TABLE public.workflows
    ADD CONSTRAINT valid_difficulty CHECK (difficulty IN ('beginner', 'intermediate', 'advanced'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'valid_status'
  ) THEN
    ALTER TABLE public.workflows
    ADD CONSTRAINT valid_status CHECK (status IN ('draft', 'published'));
  END IF;
END $$;

-- Indexes für Performance und Suche
CREATE INDEX IF NOT EXISTS idx_workflows_category_id ON public.workflows(category_id);
CREATE INDEX IF NOT EXISTS idx_workflows_status ON public.workflows(status);
CREATE INDEX IF NOT EXISTS idx_workflows_featured ON public.workflows(featured);
CREATE INDEX IF NOT EXISTS idx_workflows_tags ON public.workflows USING GIN(tags);
CREATE INDEX IF NOT EXISTS idx_workflows_tool ON public.workflows(tool);
CREATE INDEX IF NOT EXISTS idx_workflows_difficulty ON public.workflows(difficulty);

-- ==============================================================================
-- STEP 3: Seed Categories
-- ==============================================================================

INSERT INTO public.categories (slug, name, description, icon, sort_order) 
VALUES
  ('writing', 'Writing', 'Create compelling content for blogs, social media, and more', '✍️', 1),
  ('marketing', 'Marketing', 'Generate ad copy, campaigns, and marketing strategies', '📣', 2),
  ('business', 'Business', 'Build reports, proposals, and business documents', '💼', 3),
  ('productivity', 'Productivity', 'Summarize, research, and organize information faster', '⚡', 4),
  ('career', 'Career', 'Craft resumes, cover letters, and prepare for interviews', '🎯', 5),
  ('development', 'Development', 'Write code, documentation, and debug faster', '💻', 6)
ON CONFLICT (slug) DO NOTHING;

-- ==============================================================================
-- STEP 4: Update existing workflows to set default status to 'published'
-- ==============================================================================

UPDATE public.workflows
SET status = 'published'
WHERE status IS NULL OR status = 'draft';

-- ==============================================================================
-- Migration Complete
-- ==============================================================================

-- Verification Query (run separately if needed):
-- SELECT * FROM public.categories ORDER BY sort_order;
-- SELECT column_name, data_type FROM information_schema.columns WHERE table_name = 'workflows';

